name: Deploy para EC2

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy API para EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copiar arquivos para EC2
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/api

      - name: Instalar NVM e Node.js
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
          source ~/.nvm/nvm.sh
          nvm install 18
          nvm use 18
          nvm alias default 18
          node -v
          npm -v

      - name: Instalar Git, Docker e Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ec2-user/api
            sudo yum update -y
            sudo amazon-linux-extras enable docker
            sudo yum install docker -y
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")')/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            sudo yum install -y git
            docker --version
            docker-compose --version
            git --version
            


      - name: Configurar variáveis de ambiente na instância
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << EOF
            echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" > /home/ec2-user/api/.env
            echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> /home/ec2-user/api/.env
            echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> /home/ec2-user/api/.env
            echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> /home/ec2-user/api/.env
            echo "DB_HOST=${{ secrets.DB_HOST }}" >> /home/ec2-user/api/.env
            echo "DB_USER=${{ secrets.DB_USER }}" >> /home/ec2-user/api/.env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> /home/ec2-user/api/.env
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> /home/ec2-user/api/.env
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> /home/ec2-user/api/.env
            echo "PORT=${{ secrets.PORT }}" >> /home/ec2-user/api/.env
            echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> /home/ec2-user/api/.env
          EOF

      - name: Instalar dependências e rodar containers
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ec2-user/api
            npm install
            sudo docker-compose build
            sudo docker-compose up -d
          EOF

      - name: Rodar a API com npm run dev
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ec2-user/api
            nohup npm run dev > /home/ec2-user/api/logs.txt 2>&1 &
          EOF





